package io.github.willqi.pizzaserver.api.entity.inventory;

/**
 * All the possible inventory slot types an inventory can have
 */
public enum InventorySlotType {
    ANVIL_ITEM,
    ANVIL_MATERIAL,
    ANVIL_RESULT,
    SMITHING_TABLE_ITEM,
    SMITHING_TABLE_MATERIAL,
    SMITHING_TABLE_RESULT,
    ARMOR,
    CONTAINER,
    BEACON_ITEM,
    BREWING_ITEM,
    BREWING_RESULT,
    BREWING_FUEL,
    PLAYER_INVENTORY,
    CRAFTING_ITEM,
    CRAFTING_RESULT,
    RECIPE_CONSTRUCTION,
    RECIPE_NATURE,
    RECIPE_ITEMS,
    RECIPE_SEARCH,
    RECIPE_SEARCH_BAR,
    RECIPE_EQUIPMENT,
    ENCHANTING_ITEM,
    ENCHANTING_FUEL,
    FURNACE_FUEL,
    FURNACE_ITEM,
    FURNACE_RESULT,
    HORSE_INVENTORY,
    HOTBAR,
    INVENTORY,
    SHULKER,
    TRADE_ITEM,
    TRADE_ITEM_2,
    TRADE_RESULT,
    OFFHAND,
    COMPCREATE_ITEM,    // ???
    COMPCREATE_RESULT,  // ???
    ELEMCONSTRUCT_ITEM, // ???
    MATREDUCE_ITEM,     // ???
    MATREDUCE_OUTPUT,   // ???
    LABTABLE_ITEM,
    LOOM_ITEM,
    LOOM_DYE,
    LOOM_MATERIAL,
    LOOM_RESULT,
    BLAST_FURNACE_ITEM,
    SMOKER_ITEM,
    TRADE2_INGREDIENT,
    TRADE2_INGREDIENT2,
    TRADE2_RESULT,
    GRINDSTONE_ITEM,
    GRINDSTONE_MATERIAL,
    GRINDSTONE_RESULT,
    STONECUTTER_ITEM,
    STONECUTTER_RESULT,
    CARTOGRAPHY_ITEM,
    CARTOGRAPHY_MATERIAL,
    CARTOGRAPHY_RESULT,
    BARREL,
    CURSOR,
    CREATIVE_RESULT
}
