package io.github.willqi.pizzaserver.server.network.protocol.versions.v419.handlers;

import com.google.common.collect.BiMap;
import com.google.common.collect.HashBiMap;
import io.github.willqi.pizzaserver.api.level.world.data.WorldSound;
import io.github.willqi.pizzaserver.api.network.protocol.packets.WorldSoundEventPacket;
import io.github.willqi.pizzaserver.server.network.protocol.versions.BasePacketBuffer;
import io.github.willqi.pizzaserver.server.network.protocol.versions.BaseProtocolPacketHandler;

import java.util.HashMap;

public class V419WorldSoundEventPacketHandler extends BaseProtocolPacketHandler<WorldSoundEventPacket> {

    protected final BiMap<WorldSound, Integer> sounds = HashBiMap.create(new HashMap<WorldSound, Integer>() {
        {
            this.put(WorldSound.ITEM_USE_ON, 0);
            this.put(WorldSound.HIT, 1);
            this.put(WorldSound.STEP, 2);
            this.put(WorldSound.FLY, 3);
            this.put(WorldSound.JUMP, 4);
            this.put(WorldSound.BREAK, 5);
            this.put(WorldSound.PLACE, 6);
            this.put(WorldSound.HEAVY_STEP, 7);
            this.put(WorldSound.GALLOP, 8);
            this.put(WorldSound.FALL, 9);
            this.put(WorldSound.AMBIENT, 10);
            this.put(WorldSound.AMBIENT_BABY, 11);
            this.put(WorldSound.AMBIENT_IN_WATER, 12);
            this.put(WorldSound.BREATHE,  13);
            this.put(WorldSound.DEATH,  14);
            this.put(WorldSound.DEATH_IN_WATER,  15);
            this.put(WorldSound.DEATH_TO_ZOMBIE,  16);
            this.put(WorldSound.HURT,  17);
            this.put(WorldSound.HURT_IN_WATER,  18);
            this.put(WorldSound.MAD,  19);
            this.put(WorldSound.BOOST,  20);
            this.put(WorldSound.BOW,  21);
            this.put(WorldSound.SQUISH_BIG,  22);
            this.put(WorldSound.SQUISH_SMALL,  23);
            this.put(WorldSound.FALL_BIG,  24);
            this.put(WorldSound.FALL_SMALL,  25);
            this.put(WorldSound.SPLASH,  26);
            this.put(WorldSound.FIZZ,  27);
            this.put(WorldSound.FLAP,  28);
            this.put(WorldSound.SWIM,  29);
            this.put(WorldSound.DRINK,  30);
            this.put(WorldSound.EAT,  31);
            this.put(WorldSound.TAKEOFF,  32);
            this.put(WorldSound.SHAKE,  33);
            this.put(WorldSound.PLOP,  34);
            this.put(WorldSound.LAND,  35);
            this.put(WorldSound.SADDLE,  36);
            this.put(WorldSound.ARMOR,  37);
            this.put(WorldSound.MOB_ARMOR_STAND_PLACE,  38);
            this.put(WorldSound.ADD_CHEST,  39);
            this.put(WorldSound.THROW,  40);
            this.put(WorldSound.ATTACK,  41);
            this.put(WorldSound.ATTACK_NODAMAGE,  42);
            this.put(WorldSound.ATTACK_STRONG,  43);
            this.put(WorldSound.WARN,  44);
            this.put(WorldSound.SHEAR,  45);
            this.put(WorldSound.MILK,  46);
            this.put(WorldSound.THUNDER,  47);
            this.put(WorldSound.EXPLODE,  48);
            this.put(WorldSound.FIRE,  49);
            this.put(WorldSound.IGNITE,  50);
            this.put(WorldSound.FUSE,  51);
            this.put(WorldSound.STARE,  52);
            this.put(WorldSound.SPAWN,  53);
            this.put(WorldSound.SHOOT,  54);
            this.put(WorldSound.BREAK_BLOCK,  55);
            this.put(WorldSound.LAUNCH,  56);
            this.put(WorldSound.BLAST,  57);
            this.put(WorldSound.LARGE_BLAST,  58);
            this.put(WorldSound.TWINKLE,  59);
            this.put(WorldSound.REMEDY,  60);
            this.put(WorldSound.UNFECT,  61);
            this.put(WorldSound.LEVELUP,  62);
            this.put(WorldSound.BOW_HIT,  63);
            this.put(WorldSound.BULLET_HIT,  64);
            this.put(WorldSound.EXTINGUISH_FIRE,  65);
            this.put(WorldSound.ITEM_FIZZ,  66);
            this.put(WorldSound.CHEST_OPEN,  67);
            this.put(WorldSound.CHEST_CLOSED,  68);
            this.put(WorldSound.SHULKERBOX_OPEN,  69);
            this.put(WorldSound.SHULKERBOX_CLOSED,  70);
            this.put(WorldSound.ENDERCHEST_OPEN,  71);
            this.put(WorldSound.ENDERCHEST_CLOSED,  72);
            this.put(WorldSound.POWER_ON,  73);
            this.put(WorldSound.POWER_OFF,  74);
            this.put(WorldSound.ATTACH,  75);
            this.put(WorldSound.DETACH,  76);
            this.put(WorldSound.DENY,  77);
            this.put(WorldSound.TRIPOD,  78);
            this.put(WorldSound.POP,  79);
            this.put(WorldSound.DROP_SLOT,  80);
            this.put(WorldSound.NOTE,  81);
            this.put(WorldSound.THORNS,  82);
            this.put(WorldSound.PISTON_IN,  83);
            this.put(WorldSound.PISTON_OUT,  84);
            this.put(WorldSound.PORTAL,  85);
            this.put(WorldSound.WATER,  86);
            this.put(WorldSound.LAVA_POP,  87);
            this.put(WorldSound.LAVA,  88);
            this.put(WorldSound.BURP,  89);
            this.put(WorldSound.BUCKET_FILL_WATER,  90);
            this.put(WorldSound.BUCKET_FILL_LAVA,  91);
            this.put(WorldSound.BUCKET_EMPTY_WATER,  92);
            this.put(WorldSound.BUCKET_EMPTY_LAVA,  93);
            this.put(WorldSound.ARMOR_EQUIP_CHAIN,  94);
            this.put(WorldSound.ARMOR_EQUIP_DIAMOND,  95);
            this.put(WorldSound.ARMOR_EQUIP_GENERIC,  96);
            this.put(WorldSound.ARMOR_EQUIP_GOLD,  97);
            this.put(WorldSound.ARMOR_EQUIP_IRON,  98);
            this.put(WorldSound.ARMOR_EQUIP_LEATHER,  99);
            this.put(WorldSound.ARMOR_EQUIP_ELYTRA, 100);
            this.put(WorldSound.RECORD_13, 101);
            this.put(WorldSound.RECORD_CAT, 102);
            this.put(WorldSound.RECORD_BLOCKS, 103);
            this.put(WorldSound.RECORD_CHIRP, 104);
            this.put(WorldSound.RECORD_FAR, 105);
            this.put(WorldSound.RECORD_MALL, 106);
            this.put(WorldSound.RECORD_MELLOHI, 107);
            this.put(WorldSound.RECORD_STAL, 108);
            this.put(WorldSound.RECORD_STRAD, 109);
            this.put(WorldSound.RECORD_WARD, 110);
            this.put(WorldSound.RECORD_11, 111);
            this.put(WorldSound.RECORD_WAIT, 112);
            this.put(WorldSound.STOP_RECORD, 113);
            this.put(WorldSound.GUARDIAN_FLOP, 114);
            this.put(WorldSound.ELDERGUARDIAN_CURSE, 115);
            this.put(WorldSound.MOB_WARNING, 116);
            this.put(WorldSound.MOB_WARNING_BABY, 117);
            this.put(WorldSound.TELEPORT, 118);
            this.put(WorldSound.SHULKER_OPEN, 119);
            this.put(WorldSound.SHULKER_CLOSE, 120);
            this.put(WorldSound.HAGGLE, 121);
            this.put(WorldSound.HAGGLE_YES, 122);
            this.put(WorldSound.HAGGLE_NO, 123);
            this.put(WorldSound.HAGGLE_IDLE, 124);
            this.put(WorldSound.CHORUSGROW, 125);
            this.put(WorldSound.CHORUSDEATH, 126);
            this.put(WorldSound.GLASS, 127);
            this.put(WorldSound.POTION_BREWED, 128);
            this.put(WorldSound.CAST_SPELL, 129);
            this.put(WorldSound.PREPARE_ATTACK, 130);
            this.put(WorldSound.PREPARE_SUMMON, 131);
            this.put(WorldSound.PREPARE_WOLOLO, 132);
            this.put(WorldSound.FANG, 133);
            this.put(WorldSound.CHARGE, 134);
            this.put(WorldSound.CAMERA_TAKE_PICTURE, 135);
            this.put(WorldSound.LEASHKNOT_PLACE, 136);
            this.put(WorldSound.LEASHKNOT_BREAK, 137);
            this.put(WorldSound.GROWL, 138);
            this.put(WorldSound.WHINE, 139);
            this.put(WorldSound.PANT, 140);
            this.put(WorldSound.PURR, 141);
            this.put(WorldSound.PURREOW, 142);
            this.put(WorldSound.DEATH_MIN_VOLUME, 143);
            this.put(WorldSound.DEATH_MID_VOLUME, 144);
            this.put(WorldSound.IMITATE_BLAZE, 145);
            this.put(WorldSound.IMITATE_CAVE_SPIDER, 146);
            this.put(WorldSound.IMITATE_CREEPER, 147);
            this.put(WorldSound.IMITATE_ELDER_GUARDIAN, 148);
            this.put(WorldSound.IMITATE_ENDER_DRAGON, 149);
            this.put(WorldSound.IMITATE_ENDERMAN, 150);

            this.put(WorldSound.IMITATE_EVOCATION_ILLAGER, 152);
            this.put(WorldSound.IMITATE_GHAST, 153);
            this.put(WorldSound.IMITATE_HUSK, 154);
            this.put(WorldSound.IMITATE_ILLUSION_ILLAGER, 155);
            this.put(WorldSound.IMITATE_MAGMA_CUBE, 156);
            this.put(WorldSound.IMITATE_POLAR_BEAR, 157);
            this.put(WorldSound.IMITATE_SHULKER, 158);
            this.put(WorldSound.IMITATE_SILVERFISH, 159);
            this.put(WorldSound.IMITATE_SKELETON, 160);
            this.put(WorldSound.IMITATE_SLIME, 161);
            this.put(WorldSound.IMITATE_SPIDER, 162);
            this.put(WorldSound.IMITATE_STRAY, 163);
            this.put(WorldSound.IMITATE_VEX, 164);
            this.put(WorldSound.IMITATE_VINDICATION_ILLAGER, 165);
            this.put(WorldSound.IMITATE_WITCH, 166);
            this.put(WorldSound.IMITATE_WITHER, 167);
            this.put(WorldSound.IMITATE_WITHER_SKELETON, 168);
            this.put(WorldSound.IMITATE_WOLF, 169);
            this.put(WorldSound.IMITATE_ZOMBIE, 170);
            this.put(WorldSound.IMITATE_ZOMBIE_PIGMAN, 171);
            this.put(WorldSound.IMITATE_ZOMBIE_VILLAGER, 172);
            this.put(WorldSound.BLOCK_END_PORTAL_FRAME_FILL, 173);
            this.put(WorldSound.BLOCK_END_PORTAL_SPAWN, 174);
            this.put(WorldSound.RANDOM_ANVIL_USE, 175);
            this.put(WorldSound.BOTTLE_DRAGONBREATH, 176);
            this.put(WorldSound.PORTAL_TRAVEL, 177);
            this.put(WorldSound.ITEM_TRIDENT_HIT, 178);
            this.put(WorldSound.ITEM_TRIDENT_RETURN, 179);
            this.put(WorldSound.ITEM_TRIDENT_RIPTIDE_1, 180);
            this.put(WorldSound.ITEM_TRIDENT_RIPTIDE_2, 181);
            this.put(WorldSound.ITEM_TRIDENT_RIPTIDE_3, 182);
            this.put(WorldSound.ITEM_TRIDENT_THROW, 183);
            this.put(WorldSound.ITEM_TRIDENT_THUNDER, 184);
            this.put(WorldSound.ITEM_TRIDENT_HIT_GROUND, 185);
            this.put(WorldSound.DEFAULT, 186);
            this.put(WorldSound.FLETCHING_TABLE_USE, 187);
            this.put(WorldSound.ELEMENT_CONSTRUCT_OPEN, 188);
            this.put(WorldSound.ICEBOMB_HIT, 189);
            this.put(WorldSound.BALLOONPOP, 190);
            this.put(WorldSound.LT_REACTION_ICEBOMB, 191);
            this.put(WorldSound.LT_REACTION_BLEACH, 192);
            this.put(WorldSound.LT_REACTION_EPASTE, 193);
            this.put(WorldSound.LT_REACTION_EPASTE2, 194);

            this.put(WorldSound.LT_REACTION_FERTILIZER, 199);
            this.put(WorldSound.LT_REACTION_FIREBALL, 200);
            this.put(WorldSound.LT_REACTION_MGSALT, 201);
            this.put(WorldSound.LT_REACTION_MISCFIRE, 202);
            this.put(WorldSound.LT_REACTION_FIRE, 203);
            this.put(WorldSound.LT_REACTION_MISCEXPLOSION, 204);
            this.put(WorldSound.LT_REACTION_MISCMYSTICAL, 205);
            this.put(WorldSound.LT_REACTION_MISCMYSTICAL2, 206);
            this.put(WorldSound.LT_REACTION_PRODUCT, 207);
            this.put(WorldSound.SPARKLER_USE, 208);
            this.put(WorldSound.GLOWSTICK_USE, 209);
            this.put(WorldSound.SPARKLER_ACTIVE, 210);
            this.put(WorldSound.CONVERT_TO_DROWNED, 211);
            this.put(WorldSound.BUCKET_FILL_FISH, 212);
            this.put(WorldSound.BUCKET_EMPTY_FISH, 213);
            this.put(WorldSound.BUBBLE_UP, 214);
            this.put(WorldSound.BUBBLE_DOWN, 215);
            this.put(WorldSound.BUBBLE_POP, 216);
            this.put(WorldSound.BUBBLE_UPINSIDE, 217);
            this.put(WorldSound.BUBBLE_DOWNINSIDE, 218);
            this.put(WorldSound.HURT_BABY, 219);
            this.put(WorldSound.DEATH_BABY, 220);
            this.put(WorldSound.STEP_BABY, 221);
            this.put(WorldSound.BORN, 223);
            this.put(WorldSound.BLOCK_TURTLE_EGG_BREAK, 224);
            this.put(WorldSound.BLOCK_TURTLE_EGG_CRACK, 225);
            this.put(WorldSound.BLOCK_TURTLE_EGG_HATCH, 226);
            this.put(WorldSound.BLOCK_TURTLE_EGG_ATTACK, 228);
            this.put(WorldSound.BEACON_ACTIVATE, 229);
            this.put(WorldSound.BEACON_AMBIENT, 230);
            this.put(WorldSound.BEACON_DEACTIVATE, 231);
            this.put(WorldSound.BEACON_POWER, 232);
            this.put(WorldSound.CONDUIT_ACTIVATE, 233);
            this.put(WorldSound.CONDUIT_AMBIENT, 234);
            this.put(WorldSound.CONDUIT_ATTACK, 235);
            this.put(WorldSound.CONDUIT_DEACTIVATE, 236);
            this.put(WorldSound.CONDUIT_SHORT, 237);
            this.put(WorldSound.SWOOP, 238);
            this.put(WorldSound.BLOCK_BAMBOO_SAPLING_PLACE, 239);
            this.put(WorldSound.PRESNEEZE, 240);
            this.put(WorldSound.SNEEZE, 241);
            this.put(WorldSound.AMBIENT_TAME, 242);
            this.put(WorldSound.SCARED, 243);
            this.put(WorldSound.BLOCK_SCAFFOLDING_CLIMB, 244);
            this.put(WorldSound.CROSSBOW_LOADING_START, 245);
            this.put(WorldSound.CROSSBOW_LOADING_MIDDLE, 246);
            this.put(WorldSound.CROSSBOW_LOADING_END, 247);
            this.put(WorldSound.CROSSBOW_SHOOT, 248);
            this.put(WorldSound.CROSSBOW_QUICK_CHARGE_START, 249);
            this.put(WorldSound.CROSSBOW_QUICK_CHARGE_MIDDLE, 250);
            this.put(WorldSound.CROSSBOW_QUICK_CHARGE_END, 251);
            this.put(WorldSound.AMBIENT_AGGRESSIVE, 252);
            this.put(WorldSound.AMBIENT_WORRIED, 253);
            this.put(WorldSound.CANT_BREED, 254);
            this.put(WorldSound.SHIELD_BLOCK, 255);
            this.put(WorldSound.LECTERN_BOOK_PLACE, 256);
            this.put(WorldSound.GRINDSTONE_USE, 257);
            this.put(WorldSound.BELL, 258);
            this.put(WorldSound.CAMPFIRE_CRACKLE, 259);
            this.put(WorldSound.ROAR, 260);
            this.put(WorldSound.STUN, 261);
            this.put(WorldSound.SWEET_BERRY_BUSH_HURT, 262);
            this.put(WorldSound.SWEET_BERRY_BUSH_PICK, 263);
            this.put(WorldSound.CARTOGRAPHY_TABLE_USE, 264);
            this.put(WorldSound.STONECUTTER_USE, 265);
            this.put(WorldSound.COMPOSTER_EMPTY, 266);
            this.put(WorldSound.COMPOSTER_FILL, 267);
            this.put(WorldSound.COMPOSTER_FILL_LAYER, 268);
            this.put(WorldSound.BARREL_OPEN, 270);
            this.put(WorldSound.BARREL_CLOSE, 271);
            this.put(WorldSound.RAID_HORN, 272);
            this.put(WorldSound.LOOM_USE, 273);
            this.put(WorldSound.AMBIENT_IN_RAID, 274);
            this.put(WorldSound.UI_CARTOGRAPHY_TABLE_USE, 275);
            this.put(WorldSound.UI_STONECUTTER_USE, 276);
            this.put(WorldSound.UI_LOOM_USE, 277);
            this.put(WorldSound.SMOKER_USE, 278);
            this.put(WorldSound.BLAST_FURNACE_USE, 279);
            this.put(WorldSound.SMITHING_TABLE_USE, 280);
            this.put(WorldSound.SCREECH, 281);
            this.put(WorldSound.SLEEP, 282);
            this.put(WorldSound.FURNACE_USE, 283);
            this.put(WorldSound.MOOSHROOM_CONVERT, 284);
            this.put(WorldSound.MILK_SUSPICIOUSLY, 285);
            this.put(WorldSound.CELEBRATE, 286);
            this.put(WorldSound.JUMP_PREVENT, 287);
            this.put(WorldSound.AMBIENT_POLLINATE, 288);
            this.put(WorldSound.BEEHIVE_DRIP, 289);
            this.put(WorldSound.BEEHIVE_ENTER, 290);
            this.put(WorldSound.BEEHIVE_EXIT, 291);
            this.put(WorldSound.BEEHIVE_WORK, 292);
            this.put(WorldSound.BEEHIVE_SHEAR, 293);
            this.put(WorldSound.HONEYBOTTLE_DRINK, 294);
            this.put(WorldSound.AMBIENT_CAVE, 295);
            this.put(WorldSound.RETREAT, 296);
            this.put(WorldSound.CONVERT_TO_ZOMBIFIED, 297);
            this.put(WorldSound.ADMIRE, 298);
            this.put(WorldSound.STEP_LAVA, 299);
            this.put(WorldSound.TEMPT, 300);
            this.put(WorldSound.PANIC, 301);
            this.put(WorldSound.ANGRY, 302);
            this.put(WorldSound.AMBIENT_WARPED_FOREST, 303);
            this.put(WorldSound.AMBIENT_SOULSAND_VALLEY, 304);
            this.put(WorldSound.AMBIENT_NETHER_WASTES, 305);
            this.put(WorldSound.AMBIENT_BASALT_DELTAS, 306);
            this.put(WorldSound.AMBIENT_CRIMSON_FOREST, 307);
            this.put(WorldSound.RESPAWN_ANCHOR_CHARGE, 308);
            this.put(WorldSound.RESPAWN_ANCHOR_DEPLETE, 309);
            this.put(WorldSound.RESPAWN_ANCHOR_SET_SPAWN, 310);
            this.put(WorldSound.RESPAWN_ANCHOR_AMBIENT, 311);
            this.put(WorldSound.SOUL_ESCAPE_QUIET, 312);
            this.put(WorldSound.SOUL_ESCAPE_LOUD, 313);
            this.put(WorldSound.RECORD_PIGSTEP, 314);
            this.put(WorldSound.LINK_COMPASS_TO_LODESTONE, 315);
            this.put(WorldSound.USE_SMITHING_TABLE, 316);
            this.put(WorldSound.EQUIP_NETHERITE, 317);
        }
    });

    @Override
    public WorldSoundEventPacket decode(BasePacketBuffer buffer) {
        WorldSoundEventPacket packet = new WorldSoundEventPacket();
        packet.setSound(this.sounds.inverse().get(buffer.readUnsignedVarInt()));
        packet.setVector3(buffer.readVector3());
        int blockId = buffer.readVarInt();
        if (blockId != -1) {
            packet.setBlock(buffer.getVersion().getBlockFromRuntimeId(blockId));
        }
        packet.setEntityType(buffer.readString());
        packet.setBaby(buffer.readBoolean());
        packet.setGlobal(buffer.readBoolean());
        return packet;
    }

    @Override
    public void encode(WorldSoundEventPacket packet, BasePacketBuffer buffer) {
        buffer.writeUnsignedVarInt(this.sounds.get(packet.getSound()));
        buffer.writeVector3(packet.getVector3());
        if (packet.getBlock().isPresent()) {
            buffer.writeVarInt(buffer.getVersion().getBlockRuntimeId(packet.getBlock().get().getBlockType().getBlockId(), packet.getBlock().get().getBlockState()));
        } else {
            buffer.writeVarInt(-1);
        }
        buffer.writeString(packet.getEntityType());
        buffer.writeBoolean(packet.isBaby());
        buffer.writeBoolean(packet.isGlobal());
    }
}
