name: Java CI with Gradle

on:
  push:
    branches: [ feat/api ]
  pull_request:
    branches: [ feat/api ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'
    - run: ./gradlew build_all --no-daemon
